- README.md
Trying to make things a little easier for xml Spring folks.
> Clear up Spring XML example

- shedlock-core/src/main/java/net/javacrumbs/shedlock/core/SchedulerLock.java
- shedlock-spring/src/main/java/net/javacrumbs/shedlock/spring/SpringLockConfigurationExtractor.java
- shedlock-spring/src/main/java/net/javacrumbs/shedlock/spring/SpringLockableTaskSchedulerFactory.java
- shedlock-spring/src/test/java/net/javacrumbs/shedlock/spring/SpringLockConfigurationExtractorTest.java
@SchedulerLock(
name = "SchedulerLockName",
lockAtMostForString = "${scheduler.lock.at.most}",
lockAtLeastForString = "${scheduler.lock.at.least}")
> Use external variable to define lock parameters

- README.md
* missing java type: example code has a compilation error
* Add Apache License Shield: see license direkt on the github page
* Upturned section: see direkt the requirements and dependencies and add spring
> Improve documentation (README)

- README.md
- shedlock-provider-hazelcast/pom.xml
- shedlock-provider-hazelcast/src/main/java/net/javacrumbs/shedlock/provider/hazelcast/HazelcastLock.java
- shedlock-provider-hazelcast/src/main/java/net/javacrumbs/shedlock/provider/hazelcast/HazelcastLockProvider.java
- shedlock-provider-hazelcast/src/test/java/net/javacrumbs/shedlock/provider/hazelcast/HazelcastLockProviderClusterTest.java
- shedlock-provider-hazelcast/src/test/java/net/javacrumbs/shedlock/provider/hazelcast/HazelcastLockProviderIntegrationTest.java
- shedlock-provider-hazelcast/src/test/resources/logback.xml
I add the support of Hazelcast for Shedlock. If you want, you can merge it into your project.
If you have some observersations / improvements contact me.
Bye
> feature : add the support of Hazelcast

- README.md
I *think* this is supposed to say "one and only one". Or maybe I'm reading it wrong.
> Readme introduction clarity

- pom.xml
- providers/redis/shedlock-provider-redis-spring-1/pom.xml
- providers/redis/shedlock-provider-redis-spring-1/src/main/java/net/javacrumbs/shedlock/provider/redis/spring1/RedisLockProvider.java
- providers/redis/shedlock-provider-redis-spring-1/src/test/java/net/javacrumbs/shedlock/provider/redis/spring1/AbstractRedisLockProviderIntegrationTest.java
- providers/redis/shedlock-provider-redis-spring-1/src/test/java/net/javacrumbs/shedlock/provider/redis/spring1/JedisLockProviderIntegrationTest.java
- providers/redis/shedlock-provider-redis-spring-1/src/test/java/net/javacrumbs/shedlock/provider/redis/spring1/LetucceLockProviderIntegrationTest.java
- providers/redis/shedlock-provider-redis-spring-1/src/test/resources/logback.xml
Based on https://github.com/rygh4775/ShedLock/pull/1/files
> #105 Add Spring Data Redis 1 module

- providers/redis/shedlock-provider-redis-spring/src/main/java/net/javacrumbs/shedlock/provider/redis/spring/RedisLockProvider.java
- providers/redis/shedlock-provider-redis-spring/src/test/java/net/javacrumbs/shedlock/provider/redis/spring/AbstractRedisLockProviderIntegrationTest.java
Adds overrides to provide a custom `RedisTemplate`. Also exposes a `Builder` to cut down on the number of constructors needed.
> Inject redis template

- README.md
- pom.xml
- providers/mongo/shedlock-provider-reactive-mongo/pom.xml
- providers/mongo/shedlock-provider-reactive-mongo/src/main/java/net/javacrumbs/shedlock/provider/reactive/mongo/ReactiveMongoLockProvider.java
- providers/mongo/shedlock-provider-reactive-mongo/src/main/java/net/javacrumbs/shedlock/provider/reactive/mongo/ReactiveMongoLockProviderLockableSubscriber.java
- providers/mongo/shedlock-provider-reactive-mongo/src/main/java/net/javacrumbs/shedlock/provider/reactive/mongo/SingleLockableSubscriber.java
- providers/mongo/shedlock-provider-reactive-mongo/src/test/java/net/javacrumbs/shedlock/provider/reactive/mongo/ReactiveReactiveMongoLockProviderIntegrationTest.java
- providers/mongo/shedlock-provider-reactive-mongo/src/test/resources/logback.xml
- shedlock-core/pom.xml
Related issue: https://github.com/lukas-krecan/ShedLock/issues/248
Since `LockProvider` is blocking I implemented it with temporal locking at subscription time.
> Reactive Mongo Support

- README.md
fix version tag misprint
`/version>` => `</version>`
> version tag misprint

- README.md
> Readme code syntax

- pom.xml
Reverts lukas-krecan/ShedLock#292
> Revert "Bump maven-surefire-plugin from 3.0.0-M4 to 3.0.0-M5"

- pom.xml
- providers/couchbase/shedlock-provider-couchbase-javaclient3/pom.xml
- providers/couchbase/shedlock-provider-couchbase-javaclient3/src/main/java/net/javacrumbs/shedlock/provider/couchbase/javaclient/Couchbase3LockProvider.java
- providers/couchbase/shedlock-provider-couchbase-javaclient3/src/test/java/net/javacrumbs/shedlock/provider/couchbase/javaclient/Couchbase3LockProviderIntegrationTest.java
- providers/couchbase/shedlock-provider-couchbase-javaclient3/src/test/resources/logback-test.xml
https://github.com/lukas-krecan/ShedLock/issues/316
> Create a couchbase provider for sdk 3.0

- README.md
Fixed few missing Maven version XML closing tags
> Fixing Maven version XML closing tags

- providers/consul/shedlock-provider-consul/src/main/java/net/javacrumbs/shedlock/provider/consul/ConsulLockProvider.java
Ready.
I don't know did I fulfill the code-style you follow, but it seems working)
> enable advanced consul-provider configuration

- README.md
- pom.xml
- providers/ignite/shedlock-provider-ignite/pom.xml
- providers/ignite/shedlock-provider-ignite/src/main/java/net/javacrumbs/shedlock/provider/ignite/IgniteLockProvider.java
- providers/ignite/shedlock-provider-ignite/src/main/java/net/javacrumbs/shedlock/provider/ignite/LockValue.java
- providers/ignite/shedlock-provider-ignite/src/test/java/net/javacrumbs/shedlock/provider/ignite/IgniteLockProviderTest.java
Hi!
Added Apache Ignite support. Please, review.
> Apache Ignite support

- micronaut/shedlock-micronaut/src/main/java/net/javacrumbs/shedlock/micronaut/internal/SchedulerLockInterceptor.java
- micronaut/shedlock-micronaut/src/test/java/net/javacrumbs/shedlock/micronaut/internal/MethodProxyAopConfig.java
- micronaut/shedlock-micronaut/src/test/java/net/javacrumbs/shedlock/micronaut/internal/MethodProxyAopTest.java
- micronaut/test/micronaut-jdbc-template/src/main/java/net/javacrumbs/micronaut/test/Configuration.java
- micronaut/test/micronaut-jdbc-template/src/main/java/net/javacrumbs/micronaut/test/ScheduledTasks.java
- micronaut/test/micronaut-jdbc-template/src/test/java/net/javacrumbs/micronaut/test/ApplicationTest.java
- micronaut/test/micronaut-jdbc/src/main/java/net/javacrumbs/micronaut/test/Configuration.java
- micronaut/test/micronaut-jdbc/src/main/java/net/javacrumbs/micronaut/test/ScheduledTasks.java
- micronaut/test/micronaut-jdbc/src/test/java/net/javacrumbs/micronaut/test/ApplicationTest.java
- pom.xml
Reverts lukas-krecan/ShedLock#695
> Revert "Bump micronaut-data.version from 2.5.0 to 3.0.1"

- providers/dynamodb/shedlock-provider-dynamodb/pom.xml
Reverts lukas-krecan/ShedLock#963
> Revert "Bump jackson-databind from 2.13.2 to 2.13.2.1 in /providers/dynamodb/shedlock-provider-dynamodb"

- providers/neo4j/shedlock-provider-neo4j/src/main/java/net/javacrumbs/shedlock/provider/neo4j/Neo4jLockProvider.java
- providers/neo4j/shedlock-provider-neo4j/src/main/java/net/javacrumbs/shedlock/provider/neo4j/Neo4jStorageAccessor.java
- providers/neo4j/shedlock-provider-neo4j/src/test/java/net/javacrumbs/shedlock/provider/neo4j/Neo4jLockProviderIntegrationTest.java
Fix issue: Unable to pass database name for the Shedlock-neo4j-provider #1025
> shedlock-provider-neo4j. Added the ability to specify a database name.

- README.md
https://github.com/lukas-krecan/ShedLock/pull/1037#issuecomment-1134894660
Separated PR only with README changes.
> README: indentation, add couchbase3, remove hazelcast

- shedlock-bom/pom.xml
> Fix wrong reference of artifact mongo reactivestreams

- README.md
- providers/opensearch/shedlock-provider-opensearch/pom.xml
- providers/opensearch/shedlock-provider-opensearch/src/main/java/net/javacrumbs/shedlock/provider/opensearch/OpenSarchLockProvider.java
- providers/opensearch/shedlock-provider-opensearch/src/main/resources/shedlock.mapping.json
- providers/opensearch/shedlock-provider-opensearch/src/main/resources/shedlock.settings.json
- providers/opensearch/shedlock-provider-opensearch/src/test/java/net/javacrumbs/container/OpenSearchContainer.java
- providers/opensearch/shedlock-provider-opensearch/src/test/java/net/javacrumbs/shedlock/provider/opensearch/OpenSarchLockProviderTest.java
- providers/opensearch/shedlock-provider-opensearch/src/test/resources/logback.xml
Provider for OpenSearch >= 1.1.0
> OpenSearch Provider

- shedlock-bom/pom.xml
> Add opensearch provider to bom module

- pom.xml
Reverts lukas-krecan/ShedLock#1142
> Revert "Bump slf4j-api from 1.7.36 to 2.0.0"

- shedlock-test-support/src/main/java/net/javacrumbs/shedlock/test/support/FuzzTester.java
So we test DefaultLockingTaskExecutor more often
> Fuzz test uses DefaultLockingTaskExecutor

- shedlock-core/src/main/java/net/javacrumbs/shedlock/core/DefaultLockingTaskExecutor.java
- shedlock-core/src/main/java/net/javacrumbs/shedlock/core/LockAssert.java
- shedlock-core/src/test/java/net/javacrumbs/shedlock/core/LockAssertTest.java
Should be better in case somebody manages to nest
same lock twice
> Use LinkedList for LockAssert

- providers/redis/shedlock-provider-redis-jedis4/src/main/java/net/javacrumbs/shedlock/provider/redis/jedis4/JedisLockProvider.java
- providers/redis/shedlock-provider-redis-jedis4/src/test/java/net/javacrumbs/shedlock/provider/redis/jedis4/JedisLockProviderIntegrationTest.java
This is PR for #1505 
Checked all tests passed
> Add ExtensibleLockProvider functionality to JedisLockProvider

- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/OracleServerTimeStatementsSource.java
Added Oracle merge statement [https://github.com/lukas-krecan/ShedLock/issues/1317](url)
> Fix bug #1317

- providers/redis/shedlock-provider-redis-quarkus2/src/main/java/net/javacrumbs/shedlock/provider/redis/quarkus/QuarkusRedisLockProvider.java
The current version uses the GET .. NX commands, which is only supported in redis version 7. Adjustments made to not use this combination, and become compatible with redis 6.2.x
> make redis provider for quarkus compatible with redis 6.2.x

- spring/shedlock-spring/src/test/java/net/javacrumbs/shedlock/spring/aop/AbstractSpringLockConfigurationExtractorTest.java
- spring/shedlock-spring/src/test/java/net/javacrumbs/shedlock/spring/aop/MethodProxyAopConfig.java
- spring/shedlock-spring/src/test/java/net/javacrumbs/shedlock/spring/aop/MethodProxyAopTest.java
- spring/shedlock-spring/src/test/java/net/javacrumbs/shedlock/spring/aop/SpringLockConfigurationExtractorTest.java
Reverts lukas-krecan/ShedLock#1757
> Revert "#1753 Tests for getting lock name from a bean"

- providers/redis/shedlock-provider-redis-spring/src/main/java/net/javacrumbs/shedlock/provider/redis/spring/RedisLockProvider.java
- providers/redis/shedlock-provider-redis-spring/src/test/java/net/javacrumbs/shedlock/provider/redis/spring/AbstractRedisLockProviderIntegrationTest.java
Adding lock extend support to spring redis lock provider
> feat(spring-redis): added lock extension for spring redis lockprovider

- providers/dynamodb/shedlock-provider-dynamodb2/src/main/java/net/javacrumbs/shedlock/provider/dynamodb2/DynamoDBLockProvider.java
Currently, the partition key name in the DynamoDB provider is static and set to _id. This limitation poses a challenge for us as we have existing tables in production where the partition key is named differently. We want to use re-use this table for shedlock.
Changes: -
Added new constructor to support partition Key name argument. To maintain compatibility with the previous constructor, I have assigned PartitionKey Name a default value of _id.
> To add support for custom PartitionKey Name in DynamoDB provider.
