lukas-krecan/ShedLock

- shedlock-provider-jedis/src/main/java/net/javacrumbs/shedlock/provider/jedis/JedisLockProvider.java
I was not able to pass JedisSentinelPool as constructor argument to JedisLockProvider, which made it impossible to use it in a Redis slave-master cluster.
> Allow any implementation of Pool<Jedis> to be passed to JedisLockProvider

- pom.xml
- shedlock-provider-redis-connectionfactory/pom.xml
- shedlock-provider-redis-connectionfactory/src/main/java/net/javacrumbs/shedlock/provider/redisconnectionfactory/RedisFactoryLockProvider.java
- shedlock-provider-redis-connectionfactory/src/test/java/net/javacrumbs/shedlock/provider/redisconnectionfactory/RedisFactoryLockProviderIntegrationTest.java
- shedlock-provider-redis-connectionfactory/src/test/resources/logback.xml
#47 for this issue.
For this implementation you need SpringBoot.
Configuration is pretty same as the Jedis version but it uses RedisConnectionFactory instead of JedisPool.
> RedisFactoryLockProvider impl

- shedlock-core/src/main/java/net/javacrumbs/shedlock/support/LockRecordRegistry.java
- shedlock-core/src/main/java/net/javacrumbs/shedlock/support/StorageBasedLockProvider.java
Many applications use ShedLock and some database migration tool.
Integration tests for those applications might need cleared and re-migrated databases (and possibly insert fresh data for the test).
When clearing and re-migrating the database however, the shedlock-table is also cleared - which is okay, since the locks should be cleared. But unfortunately, this is not sufficcient, as Shedlock maintains a list of recently created locks in memory. These recently created locks cache is not accessible from the integration tests as they are `private final` fields instantiated without dependency-injection.
Currently, this restriction is bypassed by using reflection during runtime and making the fields accessible.
This PR resolves this problem. It allows to clear the memory-maintained locks …
> clearing of LockRegistry

- README.md
Using RedisConnectionFactory instead of (perhaps a copy/pasted leftover) JedisPool.
> Fixing RedisConnectionFactory sample

- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/JdbcTemplateLockProvider.java
- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/JdbcTemplateStorageAccessor.java
use jdbcTemplate (which internally uses DataSourceUtils.getConnection())
use @Transactional with Propagation.REQUIRES_NEW
I think using connection.setAutoCommit(true) might lead to problems especially when using JTA transactions, so I propose changing at least JdbcTemplateStorageAccessor to use Springs @Transactional annotation. Additionally, JdbcTemplateLockProvider can use an existing JdbcTemplate.
> be transaction friendly

- providers/mongo/shedlock-provider-mongo/src/test/java/net/javacrumbs/shedlock/provider/mongo/MongoLockProviderIntegrationTest.java
- shedlock-test-support/src/main/java/net/javacrumbs/shedlock/test/support/AbstractLockProviderIntegrationTest.java
The properties tested in the abstract test suite should still hold, even when the lock provider is created on demand (it's synonymous to multiple clients trying to acquire the lock). Unfortunately, when only a single instance is used in the test, it's easy to make an uncaught mistake when writing a custom implementation. In my case I've made an error of using regular `set` updates in my `insertRecord` implementation (instead of correct `setOnInsert`) and all tests still passed.
> Don't cache MongoLockProvider in the integration test

- shedlock-core/src/main/java/net/javacrumbs/shedlock/support/Utils.java
Getting the hostname is quite costly. Especially on slow networks. Since it won't change, caching it seems the good way to do it.
> Init hostname once

- providers/dynamodb/shedlock-provider-dynamodb/src/main/java/net/javacrumbs/shedlock/provider/dynamodb/DynamoDBLockProvider.java
- providers/dynamodb/shedlock-provider-dynamodb/src/main/java/net/javacrumbs/shedlock/provider/dynamodb/DynamoDBUtils.java
Just minor after cleanups of imports and adding Copyright header to Utils class. Forgot those earlier and somehow IDEA didn't pick the imports up.
> DynamoDB: Cleanup imports and add copyright header

- spring/shedlock-spring/src/main/java/net/javacrumbs/shedlock/spring/internal/SpringLockConfigurationExtractor.java
- spring/shedlock-spring/src/test/java/net/javacrumbs/shedlock/spring/aop/MethodProxyAopConfig.java
- spring/shedlock-spring/src/test/java/net/javacrumbs/shedlock/spring/aop/MethodProxyAopTest.java
Please correct me if I am wrong.
Currently class level SchedulerLock annotation is not found (PROXY_METHOD mode). There are two proxy tests for JDK and class proxies in internal.SpringLockConfigurationExtractorTest. But neither one tests regular Spring bean (implementing interface) to be proxied by ShedLock.
> Finding class level annotation in proxy method mode

- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/Db2ServerTimeStatementsSource.java
- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/H2ServerTimeStatementsSource.java
- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/HsqlServerTimeStatementsSource.java
- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/MsSqlServerTimeStatementsSource.java
- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/MySqlServerTimeStatementsSource.java
- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/OracleServerTimeStatementsSource.java
- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/PostgresSqlServerTimeStatementsSource.java
- providers/jdbc/shedlock-provider-jdbc-template/src/test/java/net/javacrumbs/shedlock/provider/jdbctemplate/AbstractJdbcTemplateStorageAccessorTest.java
- providers/jdbc/shedlock-provider-jdbc-template/src/test/java/net/javacrumbs/shedlock/provider/jdbctemplate/Db2JdbcTemplateStorageAccessorTest.java
- providers/jdbc/shedlock-provider-jdbc-template/src/test/java/net/javacrumbs/shedlock/provider/jdbctemplate/H2JdbcTemplateStorageAccessorTest.java
- providers/jdbc/shedlock-provider-jdbc-template/src/test/java/net/javacrumbs/shedlock/provider/jdbctemplate/HsqlJdbcTemplateStorageAccessorTest.java
- providers/jdbc/shedlock-provider-jdbc-template/src/test/java/net/javacrumbs/shedlock/provider/jdbctemplate/MariaDbJdbcTemplateStorageAccessorTest.java
- providers/jdbc/shedlock-provider-jdbc-template/src/test/java/net/javacrumbs/shedlock/provider/jdbctemplate/MsSqlJdbcTemplateStorageAccessorTest.java
- providers/jdbc/shedlock-provider-jdbc-template/src/test/java/net/javacrumbs/shedlock/provider/jdbctemplate/MySqlJdbcTemplateStorageAccessorTest.java
- providers/jdbc/shedlock-provider-jdbc-template/src/test/java/net/javacrumbs/shedlock/provider/jdbctemplate/OracleJdbcTemplateStorageAccessorTest.java
- providers/jdbc/shedlock-provider-jdbc-template/src/test/java/net/javacrumbs/shedlock/provider/jdbctemplate/PostgresJdbcTemplateStorageAccessorTest.java
- providers/jdbc/shedlock-test-support-jdbc/src/main/java/net/javacrumbs/shedlock/test/support/jdbc/MariaDbConfig.java
- providers/jdbc/shedlock-test-support-jdbc/src/main/java/net/javacrumbs/shedlock/test/support/jdbc/MySqlConfig.java
Bugfix - ServerTimeStatementsSource strategies generate incorrect/ambiguous update statements that can lead to false lock information.
Fixes #243
> Bugfix - ServerTimeStatementsSource strategies

- README.md
- providers/consul/shedlock-provider-consul/src/main/java/net/javacrumbs/shedlock/provider/consul/ConsulLockProvider.java
Hi, it seems I missed the shutdown hook in my previous PR. I've added it and also added the close() method that will be automatically detected by spring.
For micronaut it's not the case as it requires an annotation for the destroy method but I don't think it's a good idea to add dependency on `javax.annotation` there so I added a commentary in the README
> Add shutdown hook for ConsulLockProvider.unlockScheduler

- README.md
- pom.xml
- providers/arangodb/shedlock-provider-arangodb/pom.xml
- providers/arangodb/shedlock-provider-arangodb/src/main/java/net/javacrumbs/shedlock/provider/arangodb/ArangoLockProvider.java
- providers/arangodb/shedlock-provider-arangodb/src/test/java/net/javacrumbs/shedlock/provider/arangodb/ArangoLockProviderIntegrationTest.java
- providers/arangodb/shedlock-provider-arangodb/src/test/resources/logback.xml
Added arangodb lock provider for usage of ShedLock with [ArangoDB](https://www.arangodb.com/) Documents. 
This lock provider uses a transaction because repsert (in arangodb insert with overwrite=true) does not support conditional checks (like in mongodb). 
The program was tested solely for our own use cases, which might differ from yours. To test the lock provider you can simply run a arangodb test instance as docker container.  (e.g.: `docker run -e ARANGO_NO_AUTH=1 --name arangodb -p 8529:8529 -d arangodb/arangodb:3.7.2 arangod --server.endpoint tcp://0.0.0.0:8529`)
<sup>Patrick Birkle <patrick.birkle@daimler.com>, Daimler TSS GmbH, [Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>
> added arangodb lock provider

- .gitignore
- providers/consul/shedlock-provider-consul/src/main/java/net/javacrumbs/shedlock/provider/consul/ConsulLockProvider.java
- providers/consul/shedlock-provider-consul/src/test/java/net/javacrumbs/shedlock/provider/consul/ConsulLockProviderIntegrationTest.java
- providers/consul/shedlock-provider-consul/src/test/java/net/javacrumbs/shedlock/provider/consul/ConsulLockProviderTest.java
This fixes #340 
Sadly, the `ConsulLockProviderIntegrationTest` is flaky on my maschine. The `fuzzTestShouldPass` fails most of the time, when I run the complete test class because a single session remains on the consul. When running this particular test alone, everything is fine. I'm not quite sure what the cause of this might be. It feels like race condition, but I didn't find an obvious cause after a quick look over the `FuzzTester` code. Any idea?
The `@AfterEach public void checkSessions()` doesn't really feel great, but I didn't find another way to check this post condition for every test properly.
Additionally, I added some files to the .gitignore (mainly eclipse files) - I hope this is alright. I can revert this change if you don't want this in this PR.
> fix consul session leak

- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/JdbcTemplateStorageAccessor.java
This enables conditions such as a name that is too long to result in an
error instead of a warning being emitted in logs, which can help
operators who alert on the basis of ERRORs. Closes #345.
> [#345] Log unexpected exceptions at ERROR level

- providers/cassandra/shedlock-provider-cassandra/src/main/java/net/javacrumbs/shedlock/provider/cassandra/CassandraLockProvider.java
- providers/cassandra/shedlock-provider-cassandra/src/main/java/net/javacrumbs/shedlock/provider/cassandra/CassandraStorageAccessor.java
- providers/cassandra/shedlock-provider-cassandra/src/test/java/net/javacrumbs/shedlock/provider/cassandra/CassandraLockProviderIntegrationTest.java
Hi Lukas,
As per our discussion in https://github.com/lukas-krecan/ShedLock/issues/357, I decided to implement the configurable column names for Cassandra provider which makes adds more flexibility to its usage. I have tested it locally and works as per expectation. But it is better if you check it once from your side as well. Please let me know if you have any queries.
**Changes:**
1. A new constructor for CassandraLockProvider is introduced which takes the parameters for "lockNameColumn", "lockUntilColumn", "lockedAtColumn" and "lockedByColumn" additionally.
2. Users can create custom Cassandra tables for shedlock and map their desired column names via the new constructor.
3. In CassandraLockProvider.java, line 28 to 30 have been newly introduced.
4. In CassandraStorageAccessor.java, …
> Support for Configurable columns in Cassandra provider.

- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/Db2ServerTimeStatementsSource.java
Getting following error in DB2:
INSERT INTO shedlock(name, lock_until, locked_at, locked_by) 
VALUES('testlockname', ADD_SECONDS(CURRENT TIMESTAMP, 10), (CURRENT TIMESTAMP - CURRENT TIMEZONE), 'testHost')
No authorized routine named "ADD_SECONDS" of type "FUNCTION" having compatible arguments was found.. SQLCODE=-440, SQLSTATE=42884, DRIVER=4.19.56
Changed to below:
INSERT INTO shedlock(name, lock_until, locked_at, locked_by) 
VALUES('testlockname', ((CURRENT TIMESTAMP - CURRENT TIMEZONE) + 10 SECONDS), (CURRENT TIMESTAMP - CURRENT TIMEZONE), 'testHost')
> Fix for  SQLCODE=-440 on DB2

- providers/hazelcast/shedlock-provider-hazelcast/src/test/java/net/javacrumbs/shedlock/provider/hazelcast/HazelcastLockProviderClusterTest.java
- providers/hazelcast/shedlock-provider-hazelcast4/src/test/java/net/javacrumbs/shedlock/provider/hazelcast4/HazelcastLockProviderClusterTest.java
Hi @lukas-krecan-lt,
I hope you remember me for my contributions for shedlock 4.19.0 release. I have recently seen a flaw in the current shedlock implementation and thus, decided to put a small implementation to make it more flexible for use. 
**Overview:** 
CAS (Compare And Set) or Lightweight transactions in Cassandra either go with SERIAL (Default) or LOCAL_SERIAL consistency level. SERIAL for multi data center and LOCAL_SERIAL for local data center. Shedlock internally uses lightweight transactions to guarantee the atomicity of the locking operations as shown in "Example 1".  CAS operations induce very high latency and high "WRITE TIMEOUTS" if the consistency is SERIAL in a multi datacenter set up. I am seeing this issue live in our production environment and when I thought to reduce …
> CAS Consistency Granularity

- README.md
- pom.xml
- providers/jdbc/shedlock-provider-micronaut-data/pom.xml
- providers/jdbc/shedlock-provider-micronaut-data/src/main/java/net/javacrumbs/shedlock/provider/micronautdata/MicronautDataLockProvider.java
- providers/jdbc/shedlock-provider-micronaut-data/src/main/java/net/javacrumbs/shedlock/provider/micronautdata/MicronautDataStorageAccessor.java
- providers/jdbc/shedlock-provider-micronaut-data/src/test/java/net/javacrumbs/shedlock/provider/micronautdata/HsqlJdbcLockProviderIntegrationTest.java
- providers/jdbc/shedlock-provider-micronaut-data/src/test/java/net/javacrumbs/shedlock/provider/micronautdata/MySqlJdbcLockProviderIntegrationTest.java
- providers/jdbc/shedlock-provider-micronaut-data/src/test/java/net/javacrumbs/shedlock/provider/micronautdata/PostgresJdbcLockProviderIntegrationTest.java
- providers/jdbc/shedlock-provider-micronaut-data/src/test/resources/logback-test.xml
This is needed when using https://github.com/micronaut-projects/micronaut-data for sql operations, as connections become automatically transaction aware.
> adding micronaut-data lock provider

- pom.xml
- providers/r2dbc/shedlock-provider-r2dbc-internal/pom.xml
- providers/r2dbc/shedlock-provider-r2dbc-internal/src/main/java/net/javacrumbs/shedlock/provider/r2dbc/internal/AbstractR2dbcStorageAccessor.java
- providers/r2dbc/shedlock-provider-r2dbc/pom.xml
- providers/r2dbc/shedlock-provider-r2dbc/src/main/java/net/javacrumbs/shedlock/provider/r2dbc/R2dbcLockProvider.java
- providers/r2dbc/shedlock-provider-r2dbc/src/main/java/net/javacrumbs/shedlock/provider/r2dbc/R2dbcStorageAccessor.java
- providers/r2dbc/shedlock-provider-r2dbc/src/test/java/net/javacrumbs/shedlock/provider/r2dbc/AbstractR2dbcTest.java
- providers/r2dbc/shedlock-provider-r2dbc/src/test/java/net/javacrumbs/shedlock/provider/r2dbc/PostgresR2dbcLockProviderIntegrationTest.java
Draft for #700.
Also, I think it makes sense to provide an alternative reactive core API and implement it for providers which use reactive API (such as Lettuce, Redisson, Mongo, Cassandra). I might try to do it if it's ok for you from an API design perspective.
> R2dbc provider

- README.md
> Fix typo `Kotling` -> `Kotlin`

- README.md
- providers/redis/shedlock-provider-redis-spring/pom.xml
- providers/redis/shedlock-provider-redis-spring/src/main/java/net/javacrumbs/shedlock/provider/redis/spring/ReactiveRedisLockProvider.java
- providers/redis/shedlock-provider-redis-spring/src/test/java/net/javacrumbs/shedlock/provider/redis/spring/AbstractReactiveRedisLockProviderIntegrationTest.java
- providers/redis/shedlock-provider-redis-spring/src/test/java/net/javacrumbs/shedlock/provider/redis/spring/SpringRedisLockProviderIntegrationTest.java
Hi team, our team uses spring boot webflux and spring-data-redis to support a highly scalable platform and didn't find any LockProvider support for ReactiveRedisConnectionFactory. It is part of the spring-data-redis. Similar to R2DBC, the only new maven dependency is `reactor-core`. May I merge this PR to improve the overall support for spring reactor project?
> Support ReactiveRedisLockProvider

- providers/couchbase/shedlock-provider-couchbase-javaclient3/src/main/java/net/javacrumbs/shedlock/provider/couchbase/javaclient3/CouchbaseLockProvider.java
- providers/couchbase/shedlock-provider-couchbase-javaclient3/src/test/java/net/javacrumbs/shedlock/provider/couchbase/javaclient3/CouchbaseLockProviderIntegrationTest.java
I made a change in couchbase provider in order to use custom collection without breaking change.
We can use a custom collection in default scope like below with the PR:
```java
new CouchbaseLockProvider(bucket.collection("lock"));
```
Or with custom scope and collection:
```java
new CouchbaseLockProvider(bucket.scope("test").collection("lock"));
```
------
Bean usage example:
```java
@Bean("lockCollection")
public Collection lockCollection(Cluster cluster) {
return cluster.bucket(getBucketName()).collection("lock");
}
@Bean
public CouchbaseLockProvider lockProvider(@Qualifier("lockCollection") Collection collection) {
return new CouchbaseLockProvider(collection);
}
```
> couchbase collection support

- README.md
The table name needs to be mentioned in the Configuration builder for the cassandra configuration to work properly.
> Updated Readme.md with Cassandra configuration

- spring/shedlock-spring/src/main/java/net/javacrumbs/shedlock/spring/ExtendedLockConfigurationExtractor.java
- spring/shedlock-spring/src/main/java/net/javacrumbs/shedlock/spring/aop/MethodProxyScheduledLockAdvisor.java
- spring/shedlock-spring/src/main/java/net/javacrumbs/shedlock/spring/aop/SpringLockConfigurationExtractor.java
- spring/shedlock-spring/src/test/java/net/javacrumbs/shedlock/spring/aop/AbstractSpringLockConfigurationExtractorTest.java
- spring/shedlock-spring/src/test/java/net/javacrumbs/shedlock/spring/aop/SpringLockConfigurationExtractorTest.java
This PR adds SpEL support to @SchedulerLock "name" attribute (#1284)
I think it does not add much complexity to ShedLock.
What do you think @lukas-krecan?
> #1284 Added SpEL support to @SchedulerLock name attribute

- README.md
- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/JdbcTemplateLockProvider.java
- providers/jdbc/shedlock-provider-jdbc-template/src/test/java/net/javacrumbs/shedlock/provider/jdbctemplate/JdbcTemplateLockProviderTest.java
Solves the issue #1362 with the possibility to define in the builder if table- and column names should be uppercase.
> Issue #1362: Give the possibility to make table- and column names uppercase

- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/JdbcTemplateStorageAccessor.java
Hello, we are getting UncategorizedSQLExceptions when trying to update records through JdbcTemplateStorageAccessor.updateRecord() , see stacktrace below. This doesn't happen continuously, but under certain conditions: 
- During the first seconds/minutes of each month. This is probably due to our project specific backups/infrastructure activities.
- Triggered by database restarts when our infrastructure team perform PostgreSQL upgrades.
My assumption is that during those database maintenance tasks transactions are marked as readonly and therefore fail. When maintenance is completed, errors don't appear anymore in our logs. This PR adds explicit handling of UncategorizedSQLException, which in my opinion doesn't change the behavior, as locks couldn't be updated anyway. With this change, we …
> Handle UncategorizedSQLException on JdbcTemplateStorageAccessor.updateRecord()

- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/DatabaseProduct.java
- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/JdbcTemplateLockProvider.java
- providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/SqlStatementsSource.java
Related to #1477 
This PR allows users to set a `DatabaseProductName` in their configuration if they wish. This should be useful to people who have trouble with the jdbc call `connection.getMetaData().getDatabaseProductName()`.
> Allow users to configure DatabaseProductName if needed

- shedlock-core/src/main/java/net/javacrumbs/shedlock/core/DefaultLockingTaskExecutor.java
- shedlock-core/src/test/java/net/javacrumbs/shedlock/core/DefaultLockingTaskExecutorTest.java
We do not need to try to lock if we already hold the lock. Moreover, the lock is not check nor released in the old solution.
> Clarify locking logic in case of reentrant locks

- micronaut/shedlock-micronaut/src/main/java/net/javacrumbs/shedlock/micronaut/internal/SchedulerLockInterceptor.java
Hi, Lukáš,
My application uses Micronaut 4, is written in Kotlin, and uses KSP for annotation processing. The annotation SchedulerLock isn't being processed and I believe it's due to SchedulerLockInterceptor's use of ConversionService<?>. ConversionService is unparameterized in Micronaut 4 so I think KSP is quietly failing to apply the interceptor as Aspect advice on my annotated method. This hopefully is backward compatible and will get my code working.
> Support Micronaut 4 ConversionService type

- .gitignore
- pom.xml
- providers/redis/shedlock-provider-redis-quarkus2/pom.xml
- providers/redis/shedlock-provider-redis-quarkus2/src/main/java/net/javacrumbs/shedlock/provider/redis/quarkus2/QuarkusRedisLockProvider.java
- providers/redis/shedlock-provider-redis-quarkus2/src/main/java/net/javacrumbs/shedlock/provider/redis/quarkus2/SchedulerLockFactory.java
- providers/redis/shedlock-provider-redis-quarkus2/src/test/java/net/javacrumbs/shedlock/provider/redis/quarkus/LockedService.java
- providers/redis/shedlock-provider-redis-quarkus2/src/test/java/net/javacrumbs/shedlock/provider/redis/quarkus/QuarkusRedisLockProviderExceptionsTest.java
- providers/redis/shedlock-provider-redis-quarkus2/src/test/java/net/javacrumbs/shedlock/provider/redis/quarkus/QuarkusRedisLockProviderIntegrationTest.java
- providers/redis/shedlock-provider-redis-quarkus2/src/test/java/net/javacrumbs/shedlock/provider/redis/quarkus/ScheduleLockProvider.java
- providers/redis/shedlock-provider-redis-quarkus2/src/test/resources/application.properties
Implementation for quakus 2x using native quarkus redis client
> shedlock-provider-redis-quarkus2 impl using vert.x redis client

- README.md
Minor typo correction in the README for Micronaut 4 integration. Using the `shedlock-micronaut` and not `shedlock-micronaut4` in Micronaut 4 results in issues configuring Shedlock.
> Fix instruction typo for Micronaut 4 integration

- pom.xml
- providers/s3/shedlock-provider-s3v2/pom.xml
- providers/s3/shedlock-provider-s3v2/src/main/java/net/javacrumbs/shedlock/provider/s3v2/Lock.java
- providers/s3/shedlock-provider-s3v2/src/main/java/net/javacrumbs/shedlock/provider/s3v2/S3LockProvider.java
- providers/s3/shedlock-provider-s3v2/src/main/java/net/javacrumbs/shedlock/provider/s3v2/S3StorageAccessor.java
- providers/s3/shedlock-provider-s3v2/src/test/java/net/javacrumbs/shedlock/provider/s3v2/S3LockProviderIntegrationTest.java
- providers/s3/shedlock-provider-s3v2/src/test/resources/logback-test.xml
- shedlock-bom/pom.xml
> S3 provider with sdk v2

- shedlock-bom/pom.xml
Hi,
we realized that shedlock-provider-jdbc was missing in the bom. I hope it's fine that I just opened a PR without creating an issue first as this is a very small and trivial change.
> Add shedlock-provider-jdbc to bom

- providers/redis/shedlock-provider-redis-jedis4/pom.xml
- providers/redis/shedlock-provider-redis-jedis4/src/main/java/net/javacrumbs/shedlock/provider/redis/jedis4/JedisLockProvider.java
- providers/redis/shedlock-provider-redis-jedis4/src/test/java/net/javacrumbs/shedlock/provider/redis/jedis4/JedisLockProviderIntegrationTest.java
- providers/redis/shedlock-provider-redis-lettuce/pom.xml
- providers/redis/shedlock-provider-redis-lettuce/src/main/java/net/javacrumbs/shedlock/provider/redis/lettuce/LettuceLockProvider.java
- providers/redis/shedlock-provider-redis-lettuce/src/test/java/net/javacrumbs/shedlock/provider/redis/lettuce/LettuceLockProviderIntegrationTest.java
- providers/redis/shedlock-provider-redis-spring/pom.xml
- providers/redis/shedlock-provider-redis-spring/src/main/java/net/javacrumbs/shedlock/provider/redis/spring/ReactiveRedisLockProvider.java
- providers/redis/shedlock-provider-redis-spring/src/main/java/net/javacrumbs/shedlock/provider/redis/spring/RedisLockProvider.java
- providers/redis/shedlock-provider-redis-spring/src/test/java/net/javacrumbs/shedlock/provider/redis/spring/AbstractRedisLockProviderIntegrationTest.java
- providers/redis/shedlock-provider-redis-spring/src/test/java/net/javacrumbs/shedlock/provider/redis/spring/SpringRedisLockProviderIntegrationTest.java
- providers/redis/shedlock-test-support-redis/pom.xml
- providers/redis/shedlock-test-support-redis/src/main/java/net/javacrumbs/shedlock/provider/redis/testsupport/AbstractExtensibleLockProviderRedisIntegrationTest.java
- shedlock-test-support/src/main/java/net/javacrumbs/shedlock/test/support/AbstractExtensibleLockProviderIntegrationTest.java
Implement Redis distributed locking respecting unique lock value to avoid removing a lock that was created by another client. (https://redis.io/docs/latest/develop/use/patterns/distributed-locks/)
> Fix for #2583

- pom.xml
- providers/jdbc/shedlock-provider-exposed/pom.xml
- providers/jdbc/shedlock-provider-exposed/src/main/kotlin/net/javacrumbs/shedlock/provider/exposed/ExposedIntervalExpression.kt
- providers/jdbc/shedlock-provider-exposed/src/main/kotlin/net/javacrumbs/shedlock/provider/exposed/ExposedLockProvider.kt
- providers/jdbc/shedlock-provider-exposed/src/main/kotlin/net/javacrumbs/shedlock/provider/exposed/ExposedStorageAccessor.kt
- providers/jdbc/shedlock-provider-exposed/src/main/kotlin/net/javacrumbs/shedlock/provider/exposed/Shedlock.kt
- providers/jdbc/shedlock-provider-exposed/src/test/kotlin/net/javacrumbs/shedlock/provider/exposed/AbstractExposedLockProviderIntegrationTest.kt
- providers/jdbc/shedlock-provider-exposed/src/test/kotlin/net/javacrumbs/shedlock/provider/exposed/H2ExposedLockProviderIntegrationTest.kt
- providers/jdbc/shedlock-provider-exposed/src/test/kotlin/net/javacrumbs/shedlock/provider/exposed/MariaDbExposedLockProviderIntegrationTest.kt
- providers/jdbc/shedlock-provider-exposed/src/test/kotlin/net/javacrumbs/shedlock/provider/exposed/MsSqlExposedLockProviderIntegrationTest.kt
- providers/jdbc/shedlock-provider-exposed/src/test/kotlin/net/javacrumbs/shedlock/provider/exposed/MysqlExposedLockProviderIntegrationTest.kt
- providers/jdbc/shedlock-provider-exposed/src/test/kotlin/net/javacrumbs/shedlock/provider/exposed/PostgresExposedLockProviderIntegrationTest.kt
- providers/jdbc/shedlock-provider-exposed/src/test/resources/logback-test.xml
I have added the Exposed provider. Currently, Exposed's R2DBC support is available in version 1.0.0-beta-2, but since it is still in beta, I proceeded with version 0.61.0 for now. 
Once version 1.0.0 is officially released, I plan to add R2DBC support.
related issue: #1232
> Add exposed provider

- providers/jdbc/shedlock-provider-exposed/src/main/kotlin/net/javacrumbs/shedlock/provider/exposed/ExposedIntervalExpression.kt
`lockAtLeastUntil greater now` should be true less often so `now` should be used more often as lock until
> Try to fix Exposed flaky tests
